# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(346, 417)
        LoginWindow.setStyleSheet("background-color: rgb(178, 254, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logButton.setGeometry(QtCore.QRect(70, 270, 201, 41))
        self.logButton.setStyleSheet("background-color:rgb(255, 170, 0); font: 75 18pt \"MS Sans Serif\";")
        self.logButton.setObjectName("logButton")
        self.regButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.regButton.setGeometry(QtCore.QRect(90, 340, 161, 41))
        self.regButton.setStyleSheet("background-color: rgb(255, 64, 64); font: 75 14pt \"MS Sans Serif\";")
        self.regButton.setObjectName("regButton")
        self.helloLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.helloLabel.setGeometry(QtCore.QRect(60, 20, 241, 51))
        self.helloLabel.setStyleSheet("font: 75 19pt \"MS Sans Serif\";")
        self.helloLabel.setObjectName("helloLabel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 320, 161, 20))
        self.label.setObjectName("label")
        self.logLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(40, 82, 51, 21))
        self.logLabel.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.logLabel.setObjectName("logLabel")
        self.pasLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pasLabel.setGeometry(QtCore.QRect(40, 170, 61, 21))
        self.pasLabel.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pasLabel.setObjectName("pasLabel")
        self.logLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.logLine.setGeometry(QtCore.QRect(40, 110, 261, 41))
        self.logLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Sans Serif\";")
        self.logLine.setObjectName("logLine")
        self.pasLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pasLine.setGeometry(QtCore.QRect(40, 200, 261, 51))
        self.pasLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Sans Serif\";\n"
"")
        self.pasLine.setObjectName("pasLine")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.logButton.setText(_translate("LoginWindow", "Войти"))
        self.regButton.setText(_translate("LoginWindow", "Регистрация"))
        self.helloLabel.setText(_translate("LoginWindow", "Добро пожаловать!"))
        self.label.setText(_translate("LoginWindow", "Впервые на нашем сайте?"))
        self.logLabel.setText(_translate("LoginWindow", "Логин"))
        self.pasLabel.setText(_translate("LoginWindow", "Пароль"))
