# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 633)
        Form.setStyleSheet("background-color: rgb(178, 254, 255)")
        self.fioLine = QtWidgets.QLineEdit(parent=Form)
        self.fioLine.setGeometry(QtCore.QRect(30, 50, 361, 31))
        self.fioLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.fioLine.setObjectName("fioLine")
        self.numLine = QtWidgets.QLineEdit(parent=Form)
        self.numLine.setGeometry(QtCore.QRect(30, 410, 361, 31))
        self.numLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"сolor: rgb(122, 122, 122)")
        self.numLine.setObjectName("numLine")
        self.cityLine = QtWidgets.QLineEdit(parent=Form)
        self.cityLine.setGeometry(QtCore.QRect(30, 110, 361, 31))
        self.cityLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.cityLine.setObjectName("cityLine")
        self.pasLine = QtWidgets.QLineEdit(parent=Form)
        self.pasLine.setGeometry(QtCore.QRect(30, 230, 361, 31))
        self.pasLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pasLine.setObjectName("pasLine")
        self.emailLine = QtWidgets.QLineEdit(parent=Form)
        self.emailLine.setGeometry(QtCore.QRect(30, 350, 361, 31))
        self.emailLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.emailLine.setObjectName("emailLine")
        self.pas2Line = QtWidgets.QLineEdit(parent=Form)
        self.pas2Line.setGeometry(QtCore.QRect(30, 290, 361, 31))
        self.pas2Line.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pas2Line.setObjectName("pas2Line")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 231, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.regButton = QtWidgets.QPushButton(parent=Form)
        self.regButton.setGeometry(QtCore.QRect(120, 570, 201, 41))
        self.regButton.setStyleSheet("background-color: rgb(255, 170, 0); \n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.regButton.setObjectName("regButton")
        self.loginLine = QtWidgets.QLineEdit(parent=Form)
        self.loginLine.setGeometry(QtCore.QRect(30, 170, 361, 31))
        self.loginLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.loginLine.setObjectName("loginLine")
        self.aboutLine = QtWidgets.QLineEdit(parent=Form)
        self.aboutLine.setGeometry(QtCore.QRect(30, 470, 361, 81))
        self.aboutLine.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.aboutLine.setObjectName("aboutLine")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(400, 170, 16, 21))
        self.label_2.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(400, 290, 16, 21))
        self.label_3.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(400, 350, 16, 21))
        self.label_4.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(400, 230, 16, 21))
        self.label_5.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(400, 410, 16, 21))
        self.label_6.setStyleSheet("\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "  Регистрация в системе"))
        self.regButton.setText(_translate("Form", "Зарегистрироваться"))
        self.label_2.setText(_translate("Form", "*"))
        self.label_3.setText(_translate("Form", "*"))
        self.label_4.setText(_translate("Form", "*"))
        self.label_5.setText(_translate("Form", "*"))
        self.label_6.setText(_translate("Form", "*"))
