# Form implementation generated from reading ui file 'miniproject4.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 406)
        MainWindow.setStyleSheet("background-color: rgb(235, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.noButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.noButton.setGeometry(QtCore.QRect(210, 50, 171, 41))
        self.noButton.setStyleSheet("background-color: rgb(255, 92, 92); \n"
"font: 75 13pt \"MS Sans Serif\";")
        self.noButton.setObjectName("noButton")
        self.noList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.noList.setGeometry(QtCore.QRect(210, 100, 171, 221))
        self.noList.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.noList.setObjectName("noList")
        self.zaList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.zaList.setGeometry(QtCore.QRect(20, 100, 171, 221))
        self.zaList.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.zaList.setObjectName("zaList")
        self.zaButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.zaButton.setGeometry(QtCore.QRect(20, 50, 171, 41))
        self.zaButton.setStyleSheet("background-color: rgb(131, 255, 124); \n"
"font: 75 13pt \"MS Sans Serif\";")
        self.zaButton.setObjectName("zaButton")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(150, 330, 101, 23))
        self.resetButton.setStyleSheet("background-color: rgb(255, 129, 90); \n"
"font: 75 13pt \"MS Sans Serif\";")
        self.resetButton.setObjectName("resetButton")
        self.labelLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.labelLine.setGeometry(QtCore.QRect(20, 10, 361, 31))
        self.labelLine.setStyleSheet("backgroud-color: rgb(255, 255, 255); font: 75 14pt \"MS Serif\";")
        self.labelLine.setText("")
        self.labelLine.setObjectName("labelLine")
        self.lcd1 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(80, 330, 64, 23))
        self.lcd1.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.lcd1.setObjectName("lcd1")
        self.lcd2 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcd2.setGeometry(QtCore.QRect(260, 330, 64, 23))
        self.lcd2.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0)")
        self.lcd2.setObjectName("lcd2")
        self.downZaButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downZaButton.setGeometry(QtCore.QRect(50, 330, 21, 23))
        self.downZaButton.setStyleSheet("background-color: rgb(255, 92, 92); ")
        self.downZaButton.setObjectName("downZaButton")
        self.upZaButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upZaButton.setGeometry(QtCore.QRect(20, 330, 21, 23))
        self.upZaButton.setStyleSheet("background-color: rgb(131, 255, 124); ")
        self.upZaButton.setObjectName("upZaButton")
        self.upNoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upNoButton.setGeometry(QtCore.QRect(330, 330, 21, 23))
        self.upNoButton.setStyleSheet("background-color: rgb(131, 255, 124); ")
        self.upNoButton.setObjectName("upNoButton")
        self.downNoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downNoButton.setGeometry(QtCore.QRect(360, 330, 21, 23))
        self.downNoButton.setStyleSheet("background-color: rgb(255, 92, 92); ")
        self.downNoButton.setObjectName("downNoButton")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(20, 360, 361, 31))
        self.addButton.setStyleSheet("background-color:rgb(255, 170, 0);\n"
"font: 75 13pt \"MS Sans Serif\";")
        self.addButton.setObjectName("addButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.noButton.setText(_translate("MainWindow", "Против"))
        self.zaButton.setText(_translate("MainWindow", "За"))
        self.resetButton.setText(_translate("MainWindow", "Сброс"))
        self.downZaButton.setText(_translate("MainWindow", "↓"))
        self.upZaButton.setText(_translate("MainWindow", "↑"))
        self.upNoButton.setText(_translate("MainWindow", "↑"))
        self.downNoButton.setText(_translate("MainWindow", "↓"))
        self.addButton.setText(_translate("MainWindow", "Добавить новое"))
