# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 503)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(235, 255, 255)")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 421, 441))
        self.tabWidget.setStyleSheet("background-color: rgb(235, 255, 255)")
        self.tabWidget.setObjectName("tabWidget")
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(5, 450, 201, 41))
        self.addButton.setStyleSheet("background-color:rgb(255, 170, 0);\n"
"font: 75 13pt \"MS Sans Serif\";")
        self.addButton.setObjectName("addButton")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(210, 450, 201, 41))
        self.resetButton.setStyleSheet("background-color: rgb(255, 0, 0); \n"
"font: 75 13pt \"MS Sans Serif\";")
        self.resetButton.setObjectName("resetButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "Добавить новую тему"))
        self.resetButton.setText(_translate("MainWindow", "Удалить"))
